name: CI/CD # 1 깃허브 액션 이름 변경
on:
  push:
    branches: [ feat/cart ]
#  pull_request:
#    branches: [ main ]

#env:
#  RESOURCE_PATH: ./src/main/resources/application.yml # application.yml 설정 파일

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      # secrets.APPLICATION이라는 이름을 깃허브의 Actions secrets and variables에 시크릿키를 만든다
      # 해당 파일에는 application.yml파일의 정보가 들어간다
      - run: touch ./src/main/resources/application.yml # 해당 경로에 파일 생성
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml # "${{ secrets.APPLICATION }}" 이 부분을 기존 yml파일의 내용을 삭제하고 추가
      - run: cat ./src/main/resources/application.yml # yml파일 내용 확인

      # gradle 버전 설정
      - name: Setup Gradle Wrapper
        run: gradle wrapper --gradle-version 8.5
        shell: bash

        #      - name: Grant execute permission for gradlew
        #        run: chmod +x ./gradlew
        #        shell: bash

        # [2]
        #      - name: Build with Gradle
        #        run: ./gradlew clean build
        #        shell: bash

        # 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
        #  run 키워드는 실행할 명령어를 입력
        # ./gradlew clean build에는 그레들을 사용해 프로젝트를 빌드 이전 상태로 돌리고 다시 빌드하는 명령어를 실행

      # 2 현재시간 가져오기
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        # josStorer/get-current-time 플로그인을 사용해서 현재시간을 가져온다(배포버전을 지정할때 사용하기 위해서)
        id: current-time
        with:
          format: "YYYY-MM-DDTHH-mm-ss"
          utcOffset: "+09:00"

      # 3 배포용 패키지 경로 저장
      - name: Set artifact
        run: echo "artifact=$(ls ./build/libs)" >> $GITHUB_ENV
        # $GITHUB_ ENV를 사용해 깃허브 워크플로 전체적으로 사용할 수 있는 환경 변수를 설정할 수 있습니다.
        shell: bash

      - name: Show artifact
        run: echo "Artifact is ${{ env.artifact }}"
        shell: bash
        # 빌드 이후에 생성된 jar 파일을 찾아 “artifact”라는 환경 변수에 값을 넣어줍니다

      # 4 빈스토크 배포
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        # einaregilsson/beanstalk-deploy 플러그인을 사용해 빈스토크 배포를 진행
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # 해당 빈스토크의 IAM의 access_key값을 작성
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: markethub-ecs-4
          environment_name: markethub-ecs-4-env
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-2
          deployment_package: ./build/libs/${{ env.artifact }}